//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculateFunding.Frontend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BreadcrumbText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BreadcrumbText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculateFunding.Frontend.Properties.BreadcrumbText", typeof(BreadcrumbText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate funding.
        /// </summary>
        public static string CalculateFunding {
            get {
                return ResourceManager.GetString("CalculateFunding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose funding specification.
        /// </summary>
        public static string ChooseFundingSpecification {
            get {
                return ResourceManager.GetString("ChooseFundingSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create dataset.
        /// </summary>
        public static string ChooseYourData {
            get {
                return ResourceManager.GetString("ChooseYourData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Calculation Versions.
        /// </summary>
        public static string CompareCalcuationVersions {
            get {
                return ResourceManager.GetString("CompareCalcuationVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare versions.
        /// </summary>
        public static string CompareVersions {
            get {
                return ResourceManager.GetString("CompareVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create calculation specification.
        /// </summary>
        public static string CreateCalculation {
            get {
                return ResourceManager.GetString("CreateCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create policy.
        /// </summary>
        public static string CreatePolicy {
            get {
                return ResourceManager.GetString("CreatePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create specification.
        /// </summary>
        public static string CreateSpecification {
            get {
                return ResourceManager.GetString("CreateSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create subpolicy.
        /// </summary>
        public static string CreateSubPolicy {
            get {
                return ResourceManager.GetString("CreateSubPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create quality assurance test.
        /// </summary>
        public static string CreateTest {
            get {
                return ResourceManager.GetString("CreateTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map data sources to datasets for a specification.
        /// </summary>
        public static string DatasetRelationships {
            get {
                return ResourceManager.GetString("DatasetRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Calculation.
        /// </summary>
        public static string EditCalculation {
            get {
                return ResourceManager.GetString("EditCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit specification.
        /// </summary>
        public static string EditSpecification {
            get {
                return ResourceManager.GetString("EditSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit subpolicy.
        /// </summary>
        public static string EditSubpolicy {
            get {
                return ResourceManager.GetString("EditSubpolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Approvals.
        /// </summary>
        public static string FundingApprovals {
            get {
                return ResourceManager.GetString("FundingApprovals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load new data source file.
        /// </summary>
        public static string LoadDatasource {
            get {
                return ResourceManager.GetString("LoadDatasource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculations.
        /// </summary>
        public static string ManageCalculations {
            get {
                return ResourceManager.GetString("ManageCalculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage data.
        /// </summary>
        public static string ManageDatasets {
            get {
                return ResourceManager.GetString("ManageDatasets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage data source files.
        /// </summary>
        public static string ManageDataSources {
            get {
                return ResourceManager.GetString("ManageDataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Policies.
        /// </summary>
        public static string ManagePolicies {
            get {
                return ResourceManager.GetString("ManagePolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        public static string ManageSpecifications {
            get {
                return ResourceManager.GetString("ManageSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality assurance.
        /// </summary>
        public static string QualityAssurance {
            get {
                return ResourceManager.GetString("QualityAssurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality assurance tests.
        /// </summary>
        public static string QualityAssuranceTests {
            get {
                return ResourceManager.GetString("QualityAssuranceTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select data source.
        /// </summary>
        public static string SelectSourceDataset {
            get {
                return ResourceManager.GetString("SelectSourceDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        public static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View QA test results.
        /// </summary>
        public static string TestScenarioResults {
            get {
                return ResourceManager.GetString("TestScenarioResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data source file.
        /// </summary>
        public static string UpdateDataSource {
            get {
                return ResourceManager.GetString("UpdateDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View calculation versions.
        /// </summary>
        public static string ViewCalculationVersions {
            get {
                return ResourceManager.GetString("ViewCalculationVersions", resourceCulture);
            }
        }
    }
}
