//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculateFunding.Frontend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BreadcrumbText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BreadcrumbText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculateFunding.Frontend.Properties.BreadcrumbText", typeof(BreadcrumbText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Funding.
        /// </summary>
        public static string CalculateFunding {
            get {
                return ResourceManager.GetString("CalculateFunding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your data.
        /// </summary>
        public static string ChooseYourData {
            get {
                return ResourceManager.GetString("ChooseYourData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Calculation Versions.
        /// </summary>
        public static string CompareCalcuationVersions {
            get {
                return ResourceManager.GetString("CompareCalcuationVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare versions.
        /// </summary>
        public static string CompareVersions {
            get {
                return ResourceManager.GetString("CompareVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create calculation specification.
        /// </summary>
        public static string CreateCalculation {
            get {
                return ResourceManager.GetString("CreateCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Policy.
        /// </summary>
        public static string CreatePolicy {
            get {
                return ResourceManager.GetString("CreatePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Specification.
        /// </summary>
        public static string CreateSpecification {
            get {
                return ResourceManager.GetString("CreateSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create subpolicy.
        /// </summary>
        public static string CreateSubPolicy {
            get {
                return ResourceManager.GetString("CreateSubPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Calculation.
        /// </summary>
        public static string EditCalculation {
            get {
                return ResourceManager.GetString("EditCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load dataset.
        /// </summary>
        public static string LoadDataset {
            get {
                return ResourceManager.GetString("LoadDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculations.
        /// </summary>
        public static string ManageCalculations {
            get {
                return ResourceManager.GetString("ManageCalculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage data.
        /// </summary>
        public static string ManageDatasets {
            get {
                return ResourceManager.GetString("ManageDatasets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage data sources.
        /// </summary>
        public static string ManageDataSources {
            get {
                return ResourceManager.GetString("ManageDataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Policies.
        /// </summary>
        public static string ManagePolicies {
            get {
                return ResourceManager.GetString("ManagePolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Specification.
        /// </summary>
        public static string ManageSpecifications {
            get {
                return ResourceManager.GetString("ManageSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select source dataset.
        /// </summary>
        public static string SelectSourceDataset {
            get {
                return ResourceManager.GetString("SelectSourceDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data source.
        /// </summary>
        public static string UpdateDataSource {
            get {
                return ResourceManager.GetString("UpdateDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View calculation versions.
        /// </summary>
        public static string ViewCalculationVersions {
            get {
                return ResourceManager.GetString("ViewCalculationVersions", resourceCulture);
            }
        }
    }
}
