//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculateFunding.Frontend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculateFunding.Frontend.Properties.PageText", typeof(PageText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve and publish funding.
        /// </summary>
        public static string ApproveAndPublishFunding {
            get {
                return ResourceManager.GetString("ApproveAndPublishFunding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve and publish chosen specification.
        /// </summary>
        public static string ApproveAndPublishFundingDescr {
            get {
                return ResourceManager.GetString("ApproveAndPublishFundingDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign dataset schema for calculation specfication.
        /// </summary>
        public static string AssignDatasetSchemaText {
            get {
                return ResourceManager.GetString("AssignDatasetSchemaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate funding.
        /// </summary>
        public static string CalculateFunding {
            get {
                return ResourceManager.GetString("CalculateFunding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate funding, quality assure the results or approve funding..
        /// </summary>
        public static string CFSubHeading {
            get {
                return ResourceManager.GetString("CFSubHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a funding stream to see approved specifications.
        /// </summary>
        public static string ChooseFundingSpecWarningText {
            get {
                return ResourceManager.GetString("ChooseFundingSpecWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map data source files to datasets for a specification.
        /// </summary>
        public static string DatasetRelationships {
            get {
                return ResourceManager.GetString("DatasetRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the data source file a dataset uses..
        /// </summary>
        public static string DatasetRelationshipsDescr {
            get {
                return ResourceManager.GetString("DatasetRelationshipsDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding streams.
        /// </summary>
        public static string FundingStreams {
            get {
                return ResourceManager.GetString("FundingStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage data.
        /// </summary>
        public static string ManageDataset {
            get {
                return ResourceManager.GetString("ManageDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage data source files or map them to datasets for a specification..
        /// </summary>
        public static string ManageDatasetDescr {
            get {
                return ResourceManager.GetString("ManageDatasetDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the specification, policies and map datasets..
        /// </summary>
        public static string ManagePolicies {
            get {
                return ResourceManager.GetString("ManagePolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies help design funding calculations to achieve specific outcomes.
        /// </summary>
        public static string ManagePoliciesHeadingText {
            get {
                return ResourceManager.GetString("ManagePoliciesHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map a data source to this specification.
        /// </summary>
        public static string SpecificationRelationshipDescr {
            get {
                return ResourceManager.GetString("SpecificationRelationshipDescr", resourceCulture);
            }
        }
    }
}
