//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculateFunding.Frontend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculateFunding.Frontend.Properties.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an allocation line.
        /// </summary>
        internal static string CalculationAllocationLineRequired {
            get {
                return ResourceManager.GetString("CalculationAllocationLineRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must give a description for the calculation.
        /// </summary>
        internal static string CalculationDescriptionRequired {
            get {
                return ResourceManager.GetString("CalculationDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must give a unique calculation name.
        /// </summary>
        internal static string CalculationNameAlreadyExists {
            get {
                return ResourceManager.GetString("CalculationNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must give a unique calculation name.
        /// </summary>
        internal static string CalculationNameRequired {
            get {
                return ResourceManager.GetString("CalculationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a policy or subpolicy.
        /// </summary>
        internal static string CalculationPolicyIdRequired {
            get {
                return ResourceManager.GetString("CalculationPolicyIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must give a description for the policy.
        /// </summary>
        internal static string PolicyDescriptionRequired {
            get {
                return ResourceManager.GetString("PolicyDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must give a unique policy name.
        /// </summary>
        internal static string PolicyNameAlreadyExists {
            get {
                return ResourceManager.GetString("PolicyNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must give a unique policy name.
        /// </summary>
        internal static string PolicyNameRequired {
            get {
                return ResourceManager.GetString("PolicyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a policy.
        /// </summary>
        internal static string PolicyParentIdRequired {
            get {
                return ResourceManager.GetString("PolicyParentIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must give a unique specification name.
        /// </summary>
        internal static string SpecificationAlreadyExists {
            get {
                return ResourceManager.GetString("SpecificationAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must give a description for the specification.
        /// </summary>
        internal static string SpecificationDescriptionRequired {
            get {
                return ResourceManager.GetString("SpecificationDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one funding stream.
        /// </summary>
        internal static string SpecificationFundingStreamRequired {
            get {
                return ResourceManager.GetString("SpecificationFundingStreamRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must give a unique specification name.
        /// </summary>
        internal static string SpecificationNameRequired {
            get {
                return ResourceManager.GetString("SpecificationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must give a description for the subpolicy.
        /// </summary>
        internal static string SubPolicyDescriptionRequired {
            get {
                return ResourceManager.GetString("SubPolicyDescriptionRequired", resourceCulture);
            }
        }
    }
}
