export enum UserPermission {
    CanCreateQaTests = "canCreateQaTests",
    CanReleaseFunding = "canReleaseFunding",
    CanApproveFunding = "canApproveFunding",
    CanRefreshFunding = "canRefreshFunding",
    CanChooseFunding = "canChooseFunding",
    CanMapDatasets = "canMapDatasets",
    CanDeleteCalculations = "canDeleteCalculations",
    CanEditCalculations = "canEditCalculations",
    CanDeleteSpecification = "canDeleteSpecification",
    CanApproveSpecification = "canApproveSpecification",
    CanEditSpecification = "canEditSpecification",
    CanCreateSpecification = "canCreateSpecification",
    CanAdministerFundingStream = "canAdministerFundingStream",
    CanEditQaTests = "canEditQaTests",
    CanDeleteQaTests = "canDeleteQaTests",
    CanCreateTemplates = "canCreateTemplates",
    CanEditTemplates = "canEditTemplates",
    CanDeleteTemplates = "canDeleteTemplates",
    CanApproveTemplates = "canApproveTemplates",
    CanApplyCustomProfilePattern = "canApplyCustomProfilePattern",
    CanAssignProfilePattern = "canAssignProfilePattern",
    CanDeleteProfilePattern = "canDeleteProfilePattern",
    CanEditProfilePattern = "canEditProfilePattern",
    CanCreateProfilePattern = "canCreateProfilePattern",
    CanRefreshPublishedQa = "canRefreshPublishedQa",
    CanUploadDataSourceFiles = "canUploadDataSourceFiles",
}