export enum UserPermission {
  CanReleaseFunding = "canReleaseFunding",
  CanApproveFunding = "canApproveFunding",
  CanRefreshFunding = "canRefreshFunding",
  CanChooseFunding = "canChooseFunding",
  CanMapDatasets = "canMapDatasets",
  CanEditCalculations = "canEditCalculations",
  CanApproveCalculations = "canApproveCalculations",
  CanApproveAnyCalculations = "canApproveAnyCalculations",
  CanApproveAllCalculations = "canApproveAllCalculations",
  CanApproveSpecification = "canApproveSpecification",
  CanEditSpecification = "canEditSpecification",
  CanCreateSpecification = "canCreateSpecification",
  CanAdministerFundingStream = "canAdministerFundingStream",
  CanCreateTemplates = "canCreateTemplates",
  CanEditTemplates = "canEditTemplates",
  CanApproveTemplates = "canApproveTemplates",
  CanApplyCustomProfilePattern = "canApplyCustomProfilePattern",
  CanAssignProfilePattern = "canAssignProfilePattern",
  CanEditProfilePattern = "canEditProfilePattern",
  CanCreateProfilePattern = "canCreateProfilePattern",
  CanRefreshPublishedQa = "canRefreshPublishedQa",
  CanUploadDataSourceFiles = "canUploadDataSourceFiles",
}
