import { Server } from "miragejs";

import { makeServer } from "../../../src/mirage";

let server: Server;

context("Funding management approval confirmation page", () => {


    before(() => {
        // @ts-ignore
        server = makeServer("test");

        server.get("/policy/configuration/DSG/FY-2021", () => {
            return {
                "organisationGroupings": [{
                    "groupTypeIdentifier": "UKPRN",
                    "groupingReason": 0,
                    "groupTypeClassification": "LegalEntity",
                    "organisationGroupTypeCode": "LocalAuthority",
                    "providerTypeMatch": [],
                    "providerStatus": null
                }, {
                    "groupTypeIdentifier": "LACode",
                    "groupingReason": 1,
                    "groupTypeClassification": "GeographicalBoundary",
                    "organisationGroupTypeCode": "LocalAuthority",
                    "providerTypeMatch": [],
                    "providerStatus": null
                }, {
                    "groupTypeIdentifier": "LocalAuthorityClassificationTypeCode",
                    "groupingReason": 1,
                    "groupTypeClassification": "GeographicalBoundary",
                    "organisationGroupTypeCode": "LocalGovernmentGroup",
                    "providerTypeMatch": [],
                    "providerStatus": null
                }, {
                    "groupTypeIdentifier": "GovernmentOfficeRegionCode",
                    "groupingReason": 1,
                    "groupTypeClassification": "GeographicalBoundary",
                    "organisationGroupTypeCode": "GovernmentOfficeRegion",
                    "providerTypeMatch": [],
                    "providerStatus": null
                }, {
                    "groupTypeIdentifier": "CountryCode",
                    "groupingReason": 1,
                    "groupTypeClassification": "GeographicalBoundary",
                    "organisationGroupTypeCode": "Country",
                    "providerTypeMatch": [],
                    "providerStatus": null
                }],
                "id": "config-DSG-FY-2021",
                "fundingStreamId": "DSG",
                "fundingPeriodId": "FY-2021",
                "defaultTemplateVersion": "1.1",
                "variations": [{ "name": "TemplateUpdated", "order": 0, "fundingLineCodes": null }, {
                    "name": "FundingSchemaUpdated",
                    "order": 1,
                    "fundingLineCodes": null
                }, { "name": "ProviderMetadata", "order": 2, "fundingLineCodes": null }, {
                    "name": "FundingUpdated",
                    "order": 4,
                    "fundingLineCodes": null
                }, { "name": "ProfilingUpdated", "order": 5, "fundingLineCodes": null }, {
                    "name": "ReProfiling",
                    "order": 6,
                    "fundingLineCodes": null
                }],
                "errorDetectors": ["TrustIdMismatchErrorDetector", "FundingLineValueProfileMismatchErrorDetector", "PostPaymentOutOfScopeProviderErrorDetector", "ProviderNotFundedErrorDetector"],
                "approvalMode": "All",
                "providerSource": "CFS",
                "paymentOrganisationSource": "PaymentOrganisationAsProvider",
                "updateCoreProviderVersion": "Manual",
                "enableUserEditableCustomProfiles": false,
                "enableUserEditableRuleBasedProfiles": false,
                "runCalculationEngineAfterCoreProviderUpdate": true,
                "enableConverterDataMerge": false,
                "successorCheck": false,
                "indicativeOpenerProviderStatus": [],
                "allowedPublishedFundingStreamsIdsToReference": [],
                "releaseManagementVariations": [],
                "releaseChannels": [],
                "releaseActionGroups": []
            };
        })
        server.get("/users/permissions/fundingstreams", () => {
            return [
                {
                    "fundingStreamName": "Dedicated Schools Grant",
                    "userId": "",
                    "fundingStreamId": "DSG",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "PE and Sport Premium Grant",
                    "userId": "",
                    "fundingStreamId": "PSG",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Academies General Annual Grant",
                    "userId": "",
                    "fundingStreamId": "GAG",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "16-19",
                    "userId": "",
                    "fundingStreamId": "1619",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Dedicated Schools Grant - Schema 1.1 Test",
                    "userId": "",
                    "fundingStreamId": "DSG11",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Dedicated Schools Grant [Automation test run]",
                    "userId": "",
                    "fundingStreamId": "DSG-AT",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "PE and Sport Premium Grant T",
                    "userId": "",
                    "fundingStreamId": "PSGT",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Non maintained special schools revenue",
                    "userId": "",
                    "fundingStreamId": "NMSS",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Basic Skills Maths Pilot",
                    "userId": "",
                    "fundingStreamId": "BSMP",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "NFF College Collaboration Fund",
                    "userId": "",
                    "fundingStreamId": "CCF",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "COVID-19 Catch Up Premium",
                    "userId": "",
                    "fundingStreamId": "COVIDCP",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Dance and Drama Award",
                    "userId": "",
                    "fundingStreamId": "DADA",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Early Adopter Development Fund (T-Levels)",
                    "userId": "",
                    "fundingStreamId": "EADF",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "National Leaders of Further Education",
                    "userId": "",
                    "fundingStreamId": "NLFE",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Pupil Premium",
                    "userId": "",
                    "fundingStreamId": "PP",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Principals Reference Group",
                    "userId": "",
                    "fundingStreamId": "PRG",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Technical Education - Employer Support Fund",
                    "userId": "",
                    "fundingStreamId": "TEESF",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Teachers Pay Grant",
                    "userId": "",
                    "fundingStreamId": "TPG",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Teachers Pension Scheme",
                    "userId": "",
                    "fundingStreamId": "TPS",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Universal Infant Free School Meals",
                    "userId": "",
                    "fundingStreamId": "UIFSM",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "FDZ",
                    "userId": "",
                    "fundingStreamId": "FDZ",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "14-16",
                    "userId": "",
                    "fundingStreamId": "1416",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Non Formula Funded Activity",
                    "userId": "",
                    "fundingStreamId": "NFF",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Non Learning Grants",
                    "userId": "",
                    "fundingStreamId": "NLG",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Auto track",
                    "userId": "",
                    "fundingStreamId": "AUTOTRACK",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "Risk Protection Arrangements",
                    "userId": "",
                    "fundingStreamId": "RPA",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "GAG Adv & Abt/Adj & Transfer deficits",
                    "userId": "",
                    "fundingStreamId": "GAGADJ",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "d4bcb0df-91b4-47a3-ac5b-ea3d4fe466a8",
                    "userId": "",
                    "fundingStreamId": "d4bcb0df-91b4-47a3-ac5b-ea3d4fe466a8",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "f4885b6d-b8fb-4517-b2e0-e8a5a699667f",
                    "userId": "",
                    "fundingStreamId": "f4885b6d-b8fb-4517-b2e0-e8a5a699667f",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "d9b15202-1adb-4b77-9b84-b0fb4b317c06",
                    "userId": "",
                    "fundingStreamId": "d9b15202-1adb-4b77-9b84-b0fb4b317c06",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "8cc7d58a-426f-4b2f-bf17-d9afaa59dcc2",
                    "userId": "",
                    "fundingStreamId": "8cc7d58a-426f-4b2f-bf17-d9afaa59dcc2",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "a92bd21e-7116-4918-afdd-8748c4d77444",
                    "userId": "",
                    "fundingStreamId": "a92bd21e-7116-4918-afdd-8748c4d77444",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "af3f4a33-3779-4814-a275-a97871338e4a",
                    "userId": "",
                    "fundingStreamId": "af3f4a33-3779-4814-a275-a97871338e4a",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "1a6ff6a6-d9c9-4d43-958a-f78fcb88aeb1",
                    "userId": "",
                    "fundingStreamId": "1a6ff6a6-d9c9-4d43-958a-f78fcb88aeb1",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "66fa927e-89c8-4628-b05a-5c76cb619a9f",
                    "userId": "",
                    "fundingStreamId": "66fa927e-89c8-4628-b05a-5c76cb619a9f",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "ILP Reconciliation",
                    "userId": "",
                    "fundingStreamId": "ILPREC",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "f4cf9aa9-5b79-4680-ae32-b40204b8dc0a",
                    "userId": "",
                    "fundingStreamId": "f4cf9aa9-5b79-4680-ae32-b40204b8dc0a",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "d9e65d64-0431-45a0-8029-f11eb5624d13",
                    "userId": "",
                    "fundingStreamId": "d9e65d64-0431-45a0-8029-f11eb5624d13",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "dbf56aec-8ee5-4700-9ed9-737dfbcdd113",
                    "userId": "",
                    "fundingStreamId": "dbf56aec-8ee5-4700-9ed9-737dfbcdd113",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "101ad94c-d4e6-4280-9f92-4dc241782f36",
                    "userId": "",
                    "fundingStreamId": "101ad94c-d4e6-4280-9f92-4dc241782f36",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "be609db0-faf9-443e-b592-0abc2a64fac7",
                    "userId": "",
                    "fundingStreamId": "be609db0-faf9-443e-b592-0abc2a64fac7",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "47dccda8-b633-4465-9e7c-ef996cabfc9c",
                    "userId": "",
                    "fundingStreamId": "47dccda8-b633-4465-9e7c-ef996cabfc9c",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "6cbfc5a9-3914-42c5-ae74-94fb258fd343",
                    "userId": "",
                    "fundingStreamId": "6cbfc5a9-3914-42c5-ae74-94fb258fd343",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "c260e304-3351-4f79-a247-6160ad876790",
                    "userId": "",
                    "fundingStreamId": "c260e304-3351-4f79-a247-6160ad876790",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "365c1d3c-aa20-47e8-90bd-adeae9dd0922",
                    "userId": "",
                    "fundingStreamId": "365c1d3c-aa20-47e8-90bd-adeae9dd0922",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "52fb3d5a-2413-497d-a0ec-baf6046dfb0e",
                    "userId": "",
                    "fundingStreamId": "52fb3d5a-2413-497d-a0ec-baf6046dfb0e",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "f0cee932-e621-4131-a20b-4349fc1c63be",
                    "userId": "",
                    "fundingStreamId": "f0cee932-e621-4131-a20b-4349fc1c63be",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "57936477-42c0-4f6c-8927-b5471312f4c5",
                    "userId": "",
                    "fundingStreamId": "57936477-42c0-4f6c-8927-b5471312f4c5",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "826c77e2-10c6-4a27-b3f4-72029660d297",
                    "userId": "",
                    "fundingStreamId": "826c77e2-10c6-4a27-b3f4-72029660d297",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "6466a81b-fa3e-4f8b-a595-11651fd06495",
                    "userId": "",
                    "fundingStreamId": "6466a81b-fa3e-4f8b-a595-11651fd06495",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "9aa0b9da-4f9e-47fa-b8e2-315fcd5f9436",
                    "userId": "",
                    "fundingStreamId": "9aa0b9da-4f9e-47fa-b8e2-315fcd5f9436",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "b585b8f2-49b4-4c0e-a512-fa3223e50e05",
                    "userId": "",
                    "fundingStreamId": "b585b8f2-49b4-4c0e-a512-fa3223e50e05",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "fe3ad0f2-097b-4dc6-8f75-43f0c0d1f282",
                    "userId": "",
                    "fundingStreamId": "fe3ad0f2-097b-4dc6-8f75-43f0c0d1f282",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                },
                {
                    "fundingStreamName": "0c233d9c-e539-4e8d-9b3a-27a985fda7c0",
                    "userId": "",
                    "fundingStreamId": "0c233d9c-e539-4e8d-9b3a-27a985fda7c0",
                    "canAdministerFundingStream": true,
                    "canCreateSpecification": true,
                    "canEditSpecification": true,
                    "canApproveSpecification": true,
                    "canEditCalculations": true,
                    "canMapDatasets": true,
                    "canChooseFunding": true,
                    "canRefreshFunding": true,
                    "canApproveFunding": true,
                    "canReleaseFunding": true,
                    "canCreateTemplates": true,
                    "canEditTemplates": true,
                    "canApproveTemplates": true,
                    "canCreateProfilePattern": true,
                    "canEditProfilePattern": true,
                    "canAssignProfilePattern": true,
                    "canApplyCustomProfilePattern": true,
                    "canApproveCalculations": true,
                    "canApproveAnyCalculations": true,
                    "canApproveAllCalculations": true,
                    "canRefreshPublishedQa": true,
                    "canUploadDataSourceFiles": true
                }
            ];
        });
        server.get("/users/permissions/fundingstreams", () => {
            return [
                {
                    "name": "EnableReactQueryDevTool",
                    "isEnabled": true
                },
                {
                    "name": "EnableSwagger",
                    "isEnabled": true
                },
                {
                    "name": "ProfilingPatternVisible",
                    "isEnabled": true
                },
                {
                    "name": "SpecToSpec",
                    "isEnabled": true
                },
                {
                    "name": "TemplateBuilderVisible",
                    "isEnabled": true
                }
            ];
        });
        server.get("/results/specification-calculation-results-metadata/4aeb22b6-50e1-48b6-9f53-613234b78a55", () => {
            return {
                "specificationId": "4aeb22b6-50e1-48b6-9f53-613234b78a55",
                "lastUpdated": "2021-01-07T12:56:37.6893023+00:00"
            };
        });
        server.post("/publishedProviders/search", () => {
            return {
                "providers": [
                    {
                        "publishedProviderVersionId": "DSG-FY-2021-10005143",
                        "providerType": "Local Authority",
                        "providerSubType": "Local Authority",
                        "localAuthority": "Bournemouth Christchurch and Poole",
                        "fundingStatus": "Draft",
                        "providerName": "BOURNEMOUTH, CHRISTCHURCH AND POOLE COUNCIL",
                        "ukprn": "10005143",
                        "upin": "",
                        "urn": "",
                        "fundingValue": 92540428.0,
                        "specificationId": "4aeb22b6-50e1-48b6-9f53-613234b78a55",
                        "fundingStreamId": "DSG",
                        "fundingPeriodId": "FY-2021",
                        "indicative": "Hide indicative allocations",
                        "isIndicative": false,
                        "hasErrors": false,
                        "errors": [],
                        "majorVersion": null,
                        "minorVersion": null
                    }
                ],
                "filteredFundingAmount": 92540428.0,
                "canPublish": false,
                "canApprove": true,
                "totalFundingAmount": 92540428.0,
                "totalProvidersToApprove": 1,
                "totalProvidersToPublish": 0,
                "totalErrorResults": 0,
                "totalResults": 1,
                "currentPage": 1,
                "startItemNumber": 1,
                "endItemNumber": 1,
                "pagerState": {
                    "displayNumberOfPages": 4,
                    "previousPage": null,
                    "nextPage": null,
                    "lastPage": 1,
                    "pages": [
                        1
                    ],
                    "currentPage": 1
                },
                "facets": [
                    {
                        "name": "providerType",
                        "facetValues": [
                            {
                                "name": "Local Authority",
                                "count": 1
                            }
                        ]
                    },
                    {
                        "name": "providerSubType",
                        "facetValues": [
                            {
                                "name": "Local Authority",
                                "count": 1
                            }
                        ]
                    },
                    {
                        "name": "localAuthority",
                        "facetValues": [
                            {
                                "name": "Bournemouth Christchurch and Poole",
                                "count": 1
                            }
                        ]
                    },
                    {
                        "name": "fundingStatus",
                        "facetValues": [
                            {
                                "name": "Draft",
                                "count": 1
                            }
                        ]
                    },
                    {
                        "name": "indicative",
                        "facetValues": [
                            {
                                "name": "Hide indicative allocations",
                                "count": 1
                            }
                        ]
                    },
                    {
                        "name": "monthYearOpened",
                        "facetValues": [
                            {
                                "name": "Any other",
                                "count": 1
                            }
                        ]
                    },
                    {
                        "name": "hasErrors",
                        "facetValues": [
                            {
                                "name": "False",
                                "count": 1
                            }
                        ]
                    }
                ]
            };
        });
        server.get("/specs/specification-summary-by-id/4aeb22b6-50e1-48b6-9f53-613234b78a55", () => {
            return {
                "providerSource": "CFS",
                "fundingPeriod": {
                    "id": "FY-2021",
                    "name": "Financial Year 2020-21"
                },
                "fundingStreams":
                    [
                        { "id": "DSG", "name": "Dedicated Schools Grant" }
                    ],
                "providerVersionId": "dsg-2019-12-16",
                "providerSnapshotId": null,
                "description": "DSG oh no no no",
                "isSelectedForFunding": true,
                "lastEditedDate": "2021-09-23T10:26:01.8370751+01:00",
                "approvalStatus": "Approved",
                "templateIds": {
                    "DSG": "1.1"
                },
                "dataDefinitionRelationshipIds":
                    [
                        "c16e5a22-65c0-4f34-af36-b398e9efe1d0",
                        "d8f77d59-fa0b-4a64-8136-dfed8a335bba",
                        "185cc786-ac1a-401a-aab1-59264724d4b0",
                        "08e9c1e0-1850-475e-a5c8-35f3eb59c929",
                        "7e34bcb4-0973-47b6-8066-0d495f37947d",
                        "5460f47e-1f0b-4ef9-acf4-c65b054b160f",
                        "aaed4bae-923e-4b08-a3cd-a574643d0b68",
                        "19e622ca-8a29-4adc-8f34-18f0a248cacb",
                        "01bd9ee5-4021-4296-a71b-ef5c29960ca2",
                        "e0672fbb-eded-484c-8e42-e8ee9ffc8288",
                        "6656ab5e-2776-47f2-9846-f27c38a0ff8e",
                        "40da96ac-5335-4b74-bce8-5735a7272412",
                        "d487f4b5-6dcd-4b6b-918c-fc870bd9d995",
                        "9f7013f5-ef76-44fd-905f-06bdc02f95fb"
                    ],
                "coreProviderVersionUpdates": "Manual",
                "id": "4aeb22b6-50e1-48b6-9f53-613234b78a55",
                "name": "GFT Dedicated Schools Grant"
            };
        });

        server.get("/account/hasConfirmedSkills", () => {
            return {}
        });


        cy.visit("/FundingManagement/Approve/Confirm/DSG/FY-2021/4aeb22b6-50e1-48b6-9f53-613234b78a55/")
    });

    afterEach(() => {
        server?.shutdown();
    })

    describe("when the page has loaded ", () => {
        it("has the correct title", () => {
            cy.findByRole("heading", {
                level: 1,
                name: "Confirm funding approval"
            }).should("exist");
        });

        it("has the correct sub-title", () => {
            cy.findByRole("heading", {
                level: 2,
                name: "Check the information below carefully before approving the funding",

            }).should("exist");
        });

        it("has the correct warning text", () => {
            cy.findByText(/The provider amount shown might not be up to date/).should("exist");
        });

        it("has the approve button visible", () => {
            cy.findByRole("button", {
                name: /Confirm approval/,
                hidden: false
            }).should("exist");
        });

        it("can approve button", () => {
            cy.findByRole("checkbox").click();
            cy.findByRole("button", {
                name: /Confirm approval/
            }).should("exist");
            cy.findByRole("button", {
                name: /Confirm approval/
            }).click();
        })
    });
})

